const BADGE_COLORS = [
  "#f44336",
  "#3f51b5",
  "#4caf50",
  "#ff9800",
  "#2196f3",
  "#374046",
  "#cddc39",
  "#2196f3",
  "#9c27b0",
  "#ffc107",
  "#009688",
  "#673ab7",
  "#ffeb3b",
  "#cddc39",
  "#795548",
];
const NAMES = [
  "Peter Brimer",
  "Tera Gaona",
  "Kandy Liston",
  "Lonna Wrede",
  "Kristie Yard",
  "Raul Host",
  "Yukiko Binger",
  "Velvet Natera",
  "Donette Ponton",
  "Loraine Grim",
  "Shyla Mable",
  "Marhta Sing",
  "Alene Munden",
  "Holley Pagel",
  "Randell Tolman",
  "Wilfred Juneau",
  "Naida Madson",
  "Marine Amison",
  "Glinda Palazzo",
  "Lupe Island",
  "Cordelia Trotta",
  "Samara Berrier",
  "Era Stepp",
  "Malka Spradlin",
  "Edward Haner",
  "Clemencia Feather",
  "Loretta Rasnake",
  "Dana Hasbrouck",
  "Sanda Nery",
  "Soo Reiling",
  "Apolonia Volk",
  "Liliana Cacho",
  "Angel Couchman",
  "Yvonne Adam",
  "Jonas Curci",
  "Tran Cesar",
  "Buddy Panos",
  "Rosita Ells",
  "Rosalind Tavares",
  "Renae Keehn",
  "Deandrea Bester",
  "Kelvin Lemmon",
  "Guadalupe Mccullar",
  "Zelma Mayers",
  "Laurel Stcyr",
  "Edyth Everette",
  "Marylin Shevlin",
  "Hsiu Blackwelder",
  "Mark Ferguson",
  "Winford Noggle",
  "Shizuko Gilchrist",
  "Roslyn Cress",
  "Nilsa Lesniak",
  "Agustin Grant",
  "Earlie Jester",
  "Libby Daigle",
  "Shanna Maloy",
  "Brendan Wilken",
  "Windy Knittel",
  "Alice Curren",
  "Eden Lumsden",
  "Klara Morfin",
  "Sherryl Noack",
  "Gala Munsey",
  "Stephani Frew",
  "Twana Anthony",
  "Mauro Matlock",
  "Claudie Meisner",
  "Adrienne Petrarca",
  "Pearlene Shurtleff",
  "Rachelle Piro",
  "Louis Cocco",
  "Susann Mcsweeney",
  "Mandi Kempker",
  "Ola Moller",
  "Leif Mcgahan",
  "Tisha Wurster",
  "Hector Pinkett",
  "Benita Jemison",
  "Kaley Findley",
  "Jim Torkelson",
  "Freda Okafor",
  "Rafaela Markert",
  "Stasia Carwile",
  "Evia Kahler",
  "Rocky Almon",
  "Sonja Beals",
  "Dee Fomby",
  "Damon Eatman",
  "Alma Grieve",
  "Linsey Bollig",
  "Stefan Cloninger",
  "Giovanna Blind",
  "Myrtis Remy",
  "Marguerita Dostal",
  "Junior Baranowski",
  "Allene Seto",
  "Margery Caves",
  "Nelly Moudy",
  "Felix Sailer",
];

export function generateRandomList(
  count = 100,
  maxX = 2000,
  maxY = 1500,
  maxWidth = 100,
  maxHeight = 50
) {
  const list = [];

  for (let i = 0; i < count; i++) {
    list.push({
      index: i,
      x: Math.round(Math.random() * maxX),
      y: Math.round(Math.random() * maxY),
      width: Math.round(80 + Math.random() * maxWidth),
      height: Math.round(30 + Math.random() * maxHeight),
      backgroudColor: BADGE_COLORS[i % BADGE_COLORS.length],
      name: NAMES[i % NAMES.length],
    });
  }

  return list;
}

export function generateRelativeRandomList(
  count = 100,
  maxX = 2000,
  maxY = 1500,
  maxWidth = 100,
  maxHeight = 50
) {
  const list = [];

  for (let i = 0; i < count; i++) {
    list.push({
      index: i,
      x: Math.round(-maxX / 2 + (Math.random() * maxX) / 2),
      y: Math.round(-maxY / 2 + (Math.random() * maxY) / 2),
      width: Math.round(80 + Math.random() * maxWidth),
      height: Math.round(30 + Math.random() * maxHeight),
      backgroudColor: BADGE_COLORS[i % BADGE_COLORS.length],
      name: NAMES[i % NAMES.length],
    });
  }

  return list;
}
